### ISSUE TITLE
How to reproduce 91% accuracy on IMDB data?

### ISSUE THREAD

**Issue by StevenLOL** [DingKe/qrnn#1]
How to reproduce 91% accuracy on IMDB data as shown in the Table 1 in your paper.

Run the code and only get 78% at epoch 15, and 77% at epoch 150

Regards

**Comment by DingKe** [comment]
I'm not the author of the reference paper. The code here is just an experimental implementation of QRNN. I only used a QRNN layer and no any hyperparameter tuning for demo purpose and didn't mean to reproduce the result in the paper in any way.
The paper uses different network structure and different preprocessing of the text (vocabulary size, max text length et al.).

**Comment by StevenLOL** [comment]
OK, thanks.
