### ISSUE TITLE
TypeError when running imbd_qrnn.py

### ISSUE THREAD

**Issue by jessicayung** [DingKe/qrnn#3]
```
$ python imbd_qrnn.py
Using Theano backend.
Build model...
Traceback (most recent call last):
  File "imbd_qrnn.py", line 29, in <module>
    kernel_constraint=maxnorm(10), bias_constraint=maxnorm(10)))
  File "/keras/models.py", line 469, in add
    output_tensor = layer(self.outputs[0])
  File "/nn_playground/qrnn/qrnn.py", line 196, in __call__
    return super(QRNN, self).__call__(inputs, **kwargs)
  File "/keras/engine/topology.py", line 596, in __call__
    output = self.call(inputs, **kwargs)
  File "/nn_playground/qrnn/qrnn.py", line 234, in call
    preprocessed_input = self.preprocess_input(inputs, training=None)
  File "/nn_playground/qrnn/qrnn.py", line 261, in preprocess_input
    inputs = K.temporal_padding(inputs, (self.window_size-1, 0))
  File "/keras/backend/theano_backend.py", line 1028, in temporal_padding
    x._keras_shape[1] + py_sum(padding),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```
Using keras 2.0.6, python 2.7.

Have tried 
(1) adding `input_shape=(maxlen, len(X_train[0]))` as an argument to the QRNN layer
- i.e. input_shape=(maxlen, 80) since X_train.shape = (25000,80)
- reason: [this fixed similar error in using Flatten layer](https://github.com/fchollet/keras/issues/1319)
- result: returned same error

(2) using the QRNN layer alone using another dataset (because I'm not sure if the `input_shape` I specified is correct

(3) Am trying to debug it by printing things now.

**Comment by MaxwellRebo** [comment]
Try using an older version of Keras. The Keras 2.0 implementation is found at https://github.com/DingKe/nn_playground/blob/master/qrnn/imbd_qrnn.py

**Comment by jessicayung** [comment]
Ah yes I should've posted this as an issue in the `nn_playground` repo. Thanks!
